-- StudyFlow persistent learning data
-- Run this once in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  class_no text not null default '12',
  target_exam text not null default 'NCERT',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.topic_mastery (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  class_no text not null,
  subject text not null,
  chapter text not null,
  topic text not null,
  mastery integer not null default 0 check (mastery between 0 and 100),
  attempts integer not null default 0,
  correct integer not null default 0,
  last_practiced_at timestamptz,
  unique(user_id, class_no, subject, chapter, topic)
);

create table if not exists public.question_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  track text not null default 'NCERT',
  class_no text,
  subject text not null,
  chapter text,
  topic text,
  question text not null,
  student_answer text,
  correct_answer text,
  is_correct boolean not null default false,
  difficulty text,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_mistakes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  chapter text,
  topic text,
  question text not null,
  student_answer text,
  correct_answer text,
  explanation text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  class_no text not null,
  subject text not null,
  minutes integer not null,
  plan jsonb not null default '[]'::jsonb,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.topic_mastery enable row level security;
alter table public.question_attempts enable row level security;
alter table public.saved_mistakes enable row level security;
alter table public.study_sessions enable row level security;

create policy "profiles own row" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "mastery own rows" on public.topic_mastery for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "attempts own rows" on public.question_attempts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "mistakes own rows" on public.saved_mistakes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "sessions own rows" on public.study_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();
