'use client';

import { useMemo, useRef, useState } from 'react';
import { BookOpen, Brain, Camera, CheckCircle2, ChevronRight, Clock3, FileText, GraduationCap, ImagePlus, LayoutDashboard, Menu, MessageCircle, Mic, Play, Search, Sparkles, Target, Trophy, X, Zap } from 'lucide-react';

const subjects = ['Mathematics','Science','Physics','Chemistry','Biology','English','Social Science'];
const classes = ['1','2','3','4','5','6','7','8','9','10','11','12'];
const topics = [
  {name:'Current Electricity',subject:'Physics',mastery:43,priority:'Critical'},
  {name:'Electrostatics',subject:'Physics',mastery:67,priority:'High'},
  {name:'Integration',subject:'Mathematics',mastery:72,priority:'High'},
  {name:'Chemical Bonding',subject:'Chemistry',mastery:88,priority:'Good'},
];
const nav = [
  ['Dashboard',LayoutDashboard],['AI Tutor',MessageCircle],['Practice',Target],['My Subjects',BookOpen],['Tests',Trophy],['Progress',Zap]
] as const;

export default function Home(){
  const [active,setActive]=useState('Dashboard'); const [classNo,setClassNo]=useState('12'); const [subject,setSubject]=useState('Physics'); const [time,setTime]=useState(30); const [q,setQ]=useState(''); const [answer,setAnswer]=useState(''); const [imageData,setImageData]=useState(''); const [loading,setLoading]=useState(false); const [mobile,setMobile]=useState(false); const [search,setSearch]=useState('');
  const visibleTopics=useMemo(()=>topics.filter(t=>!search || `${t.name} ${t.subject}`.toLowerCase().includes(search.toLowerCase())),[search]);
  async function ask(){ if(!q.trim() && !imageData) return; setLoading(true); setAnswer(''); try{ const r=await fetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,classNo,subject,imageData})}); const d=await r.json(); setAnswer(d.answer || d.error || 'I could not generate an answer.'); }catch{setAnswer('Unable to reach the AI service. Please try again.');} finally{setLoading(false);} }
  function go(label:string){setActive(label);setMobile(false);window.scrollTo({top:0,behavior:'smooth'});}
  return <main className="min-h-screen grid-bg"><div className="flex min-h-screen">
    <aside className={`${mobile?'translate-x-0':'-translate-x-full'} fixed inset-y-0 left-0 z-50 w-72 border-r border-slate-200 bg-white transition-transform lg:static lg:translate-x-0`}><div className="flex h-full flex-col p-5">
      <div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#12395b] text-white"><GraduationCap size={21}/></div><div><b className="text-lg tracking-tight">StudyFlow</b><div className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Adaptive learning</div></div></div><button className="lg:hidden" onClick={()=>setMobile(false)}><X/></button></div>
      <div className="mb-3 px-2 text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Workspace</div><nav className="space-y-1">{nav.map(([label,Icon])=><button key={label} onClick={()=>go(label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${active===label?'bg-[#12395b] text-white':'text-slate-500 hover:bg-slate-50 hover:text-slate-900'}`}><Icon size={18}/>{label}</button>)}</nav>
      <div className="mt-auto rounded-2xl app-gradient p-4 text-white"><Brain size={18}/><b className="mt-3 block text-sm">StudyFlow AI</b><p className="mt-1 text-xs leading-5 text-blue-100">Learn, practise, evaluate and adapt — chapter by chapter.</p><button onClick={()=>go('AI Tutor')} className="mt-3 text-xs font-bold">Open tutor →</button></div>
    </div></aside>
    <section className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-slate-200 bg-white/90 px-5 backdrop-blur lg:px-10"><div className="flex items-center gap-3"><button className="rounded-xl p-2 lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div><p className="text-xs font-semibold text-slate-400">Saturday, August 15</p><h1 className="text-xl font-extrabold">{active==='Dashboard'?'Good morning, Student 👋':active}</h1></div></div><div className="hidden items-center gap-2 sm:flex"><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2"><Search size={15} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-40 text-sm outline-none" placeholder="Search topics"/></div><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#1769e0] text-sm font-bold text-white">S</div></div></header>
      <div className="mx-auto max-w-[1450px] space-y-6 p-5 lg:p-10">
        {active==='Dashboard' && <Dashboard go={go} classNo={classNo} setClassNo={setClassNo} subject={subject} setSubject={setSubject} time={time} setTime={setTime} visibleTopics={visibleTopics}/>} 
        {active==='AI Tutor' && <Tutor q={q} setQ={setQ} answer={answer} loading={loading} ask={ask} classNo={classNo} subject={subject} imageData={imageData} setImageData={setImageData}/>} 
        {active==='Practice' && <Practice classNo={classNo} subject={subject} setSubject={setSubject}/>} 
        {active==='My Subjects' && <Subjects classNo={classNo} setClassNo={setClassNo} subject={subject} setSubject={setSubject}/>} 
        {active==='Tests' && <Tests go={go}/>} 
        {active==='Progress' && <Progress/>}
        <footer className="flex flex-col gap-2 border-t border-slate-200 py-6 text-xs text-slate-400 sm:flex-row sm:justify-between"><span>StudyFlow AI • Adaptive learning platform</span><span>NCERT-aligned learning • JEE/NEET practice paths</span></footer>
      </div></section></div></main>
}

function Dashboard({go,classNo,setClassNo,subject,setSubject,time,setTime,visibleTopics}:{go:(s:string)=>void;classNo:string;setClassNo:(s:string)=>void;subject:string;setSubject:(s:string)=>void;time:number;setTime:(n:number)=>void;visibleTopics:any[]}){return <>
  <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><div className="relative overflow-hidden rounded-3xl app-gradient p-7 text-white lg:p-9"><div className="relative max-w-2xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold"><Sparkles size={13}/> Adaptive learning engine</div><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Know what to study.<br/><span className="text-blue-200">Know why it matters.</span></h2><p className="mt-4 max-w-xl text-sm leading-6 text-blue-50/80">StudyFlow builds chapter-wise learning paths for every class, then adapts practice to your performance.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>go('Practice')} className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-[#12395b]">Start practice <Arrow/></button><button onClick={()=>go('AI Tutor')} className="rounded-xl border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-bold">Ask AI Tutor</button></div></div></div>
  <div className="card rounded-3xl p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Exam readiness</p><p className="mt-1 text-3xl font-black">78%</p></div><div className="relative flex h-20 w-20 items-center justify-center"><div className="ring-gradient absolute inset-0 rounded-full"/><span className="relative z-10 text-sm font-black">Good</span></div></div><Metric l="Syllabus coverage" v={91}/><Metric l="Concept mastery" v={73}/><Metric l="Practice strength" v={69}/><button onClick={()=>go('Progress')} className="mt-5 w-full rounded-xl bg-slate-50 px-4 py-3 text-left text-xs font-bold text-slate-600">View readiness report →</button></div></div>
  <div className="grid gap-5 md:grid-cols-3"><Stat title="Study streak" value="12 days" note="Personal best: 18"/><Stat title="Questions solved" value="184" note="76% accuracy"/><Stat title="Weak topics" value="3" note="Prioritised by AI"/></div>
  <div className="grid gap-6 xl:grid-cols-[1.3fr_1fr]"><section className="card rounded-3xl p-6"><div className="flex items-center justify-between"><div><h3 className="text-lg font-extrabold">Priority topics</h3><p className="mt-1 text-sm text-slate-500">Highest-value topics for your next session.</p></div><button onClick={()=>go('Practice')} className="text-xs font-bold text-[#1769e0]">Practice all</button></div><div className="mt-5 space-y-3">{visibleTopics.map(t=><button onClick={()=>go('Practice')} key={t.name} className="flex w-full items-center gap-4 rounded-2xl border border-slate-100 p-3 text-left hover:border-blue-200 hover:shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-50 text-lg">{t.subject==='Physics'?'⚡':t.subject==='Chemistry'?'⚗':'∫'}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><b className="truncate text-sm">{t.name}</b><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">{t.priority}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#1769e0]" style={{width:`${t.mastery}%`}}/></div></div><ChevronRight size={16} className="text-slate-300"/></button>)}</div></section>
  <section className="card rounded-3xl p-6"><h3 className="text-lg font-extrabold">Build a study session</h3><p className="mt-1 text-sm text-slate-500">Choose your class, subject and available time.</p><div className="mt-5 grid grid-cols-2 gap-2"><select value={classNo} onChange={e=>setClassNo(e.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm"><option value="12">Class 12</option><option value="11">Class 11</option><option value="10">Class 10</option><option value="9">Class 9</option></select><select value={subject} onChange={e=>setSubject(e.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm"><option>Physics</option><option>Chemistry</option><option>Mathematics</option><option>Biology</option></select></div><div className="mt-4 grid grid-cols-3 gap-2">{[15,30,60].map(n=><button key={n} onClick={()=>setTime(n)} className={`rounded-xl border p-3 text-sm font-bold ${time===n?'border-[#1769e0] bg-blue-50 text-[#1769e0]':'border-slate-200 text-slate-500'}`}>{n} min</button>)}</div><div className="mt-5 rounded-2xl bg-slate-50 p-4"><b className="text-xs uppercase tracking-wider text-slate-400">Recommended</b><p className="mt-2 text-sm font-bold">Revise weak topic → {Math.round(time*.45)} min</p><p className="mt-1 text-sm font-bold">Topic practice → {Math.round(time*.45)} min</p><p className="mt-1 text-sm font-bold">Active recall → {Math.max(2,Math.round(time*.1))} min</p></div><button onClick={()=>go('Practice')} className="btn-primary mt-4 flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-bold">Start session <Play size={15} fill="currentColor"/></button></section></div>
</>}

function Tutor({q,setQ,answer,loading,ask,classNo,subject,imageData,setImageData}:{q:string;setQ:(s:string)=>void;answer:string;loading:boolean;ask:()=>void;classNo:string;subject:string;imageData:string;setImageData:(s:string)=>void}){
  const [listening,setListening]=useState(false);
  const recognitionRef=useRef<any>(null);
  const fileRef=useRef<HTMLInputElement>(null);

  function startVoice(){
    const SpeechRecognition=(window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if(!SpeechRecognition){ alert('Voice input is not supported in this browser. Try Chrome on Android or use the photo/text option.'); return; }
    if(listening){ recognitionRef.current?.stop(); setListening(false); return; }
    const recognition=new SpeechRecognition();
    recognition.lang='en-IN'; recognition.interimResults=false; recognition.continuous=false;
    recognition.onstart=()=>setListening(true);
    recognition.onresult=(event:any)=>{ const transcript=event.results?.[0]?.[0]?.transcript || ''; setQ(`${q ? `${q} ` : ''}${transcript}`.trim()); };
    recognition.onerror=()=>setListening(false);
    recognition.onend=()=>setListening(false);
    recognitionRef.current=recognition;
    recognition.start();
  }

  function handlePhoto(file:File){
    if(!file.type.startsWith('image/')) return;
    const reader=new FileReader();
    reader.onload=()=>{
      const img=new Image();
      img.onload=()=>{
        const max=1600; const scale=Math.min(1,max/Math.max(img.width,img.height));
        const canvas=document.createElement('canvas'); canvas.width=Math.max(1,Math.round(img.width*scale)); canvas.height=Math.max(1,Math.round(img.height*scale));
        const ctx=canvas.getContext('2d'); if(!ctx) return;
        ctx.drawImage(img,0,0,canvas.width,canvas.height);
        setImageData(canvas.toDataURL('image/jpeg',0.82));
      };
      img.src=String(reader.result);
    };
    reader.readAsDataURL(file);
  }

  return <section className="card mx-auto max-w-4xl rounded-3xl p-6 lg:p-9"><div className="flex items-start gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-[#1769e0]"><Brain/></div><div><h2 className="text-2xl font-black">AI Tutor</h2><p className="mt-1 text-sm text-slate-500">Class {classNo} • {subject} • Explain, solve, quiz or guide me.</p></div></div>
    <div className="mt-7"><div className="relative"><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask a question, paste an exam problem, or use your voice..." className="min-h-36 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 pr-14 text-sm outline-none focus:border-blue-400 focus:bg-white"/><button type="button" onClick={startVoice} aria-label={listening?'Stop voice input':'Start voice input'} className={`absolute bottom-3 right-3 flex h-10 w-10 items-center justify-center rounded-full ${listening?'bg-red-50 text-red-600':'bg-white text-slate-500'} border border-slate-200 shadow-sm`}><Mic size={18}/></button></div>
    {imageData&&<div className="mt-3 flex items-start gap-3 rounded-2xl border border-blue-100 bg-blue-50/50 p-3"><img src={imageData} alt="Doubt preview" className="h-24 w-24 rounded-xl border border-slate-200 object-cover"/><div className="min-w-0 flex-1"><b className="text-sm">Doubt photo attached</b><p className="mt-1 text-xs text-slate-500">StudyFlow will read the question, equations and diagrams.</p><button type="button" onClick={()=>setImageData('')} className="mt-2 text-xs font-bold text-red-600">Remove photo</button></div></div>}
    <div className="mt-3 flex flex-wrap gap-2"><input ref={fileRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>{const f=e.target.files?.[0]; if(f) handlePhoto(f); e.currentTarget.value='';}}/><button type="button" onClick={()=>fileRef.current?.click()} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:border-blue-300 hover:text-[#1769e0]"><ImagePlus size={17}/> Upload doubt photo</button><button type="button" onClick={()=>fileRef.current?.click()} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:border-blue-300 hover:text-[#1769e0]"><Camera size={17}/> Take a photo</button><span className="flex items-center px-2 text-xs text-slate-400">Tip: crop the question clearly for better results.</span></div>
    <button disabled={loading || (!q.trim()&&!imageData)} onClick={ask} className="btn-primary mt-3 rounded-xl px-5 py-3 text-sm font-bold disabled:opacity-50">{loading?'Thinking…':imageData?'Solve this doubt':'Ask StudyFlow AI'}</button></div>{answer&&<div className="fade-up mt-6 rounded-2xl border border-blue-100 bg-blue-50/60 p-5 text-sm leading-7 whitespace-pre-wrap"><b className="text-[#1769e0]">StudyFlow AI</b><div className="mt-2">{answer}</div></div>}</section>
}
function Practice({classNo,subject,setSubject}:{classNo:string;subject:string;setSubject:(s:string)=>void}){const [topic,setTopic]=useState('Current Electricity');const [level,setLevel]=useState('Exam');const [started,setStarted]=useState(false);return <section className="card rounded-3xl p-6 lg:p-9"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-black">Topic Practice</h2><p className="mt-1 text-sm text-slate-500">Adaptive questions for Class {classNo}, chapter by chapter.</p></div><Target className="text-[#1769e0]"/></div><div className="mt-6 grid gap-3 md:grid-cols-3"><select value={subject} onChange={e=>setSubject(e.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm"><option>Physics</option><option>Chemistry</option><option>Mathematics</option><option>Biology</option></select><select value={topic} onChange={e=>setTopic(e.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm"><option>Current Electricity</option><option>Electrostatics</option><option>Ray Optics</option><option>Semiconductors</option></select><select value={level} onChange={e=>setLevel(e.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm"><option>Basic</option><option>Application</option><option>Exam</option><option>JEE / NEET</option></select></div><div className="mt-6 rounded-2xl bg-slate-50 p-5"><b>Practice path</b><div className="mt-3 grid gap-2 text-sm text-slate-600 md:grid-cols-3"><span>1. Concept check</span><span>2. {level} questions</span><span>3. Mistake analysis</span></div></div><button onClick={()=>setStarted(true)} className="btn-primary mt-5 rounded-xl px-5 py-3 text-sm font-bold">{started?'Practice session ready':'Generate 10 questions'}</button>{started&&<div className="fade-up mt-5 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-800">Question set generated for <b>{topic}</b>. The AI will adjust difficulty after each answer.</div>}</section>}
function Subjects({classNo,setClassNo,subject,setSubject}:{classNo:string;setClassNo:(s:string)=>void;subject:string;setSubject:(s:string)=>void}){return <section className="card rounded-3xl p-6 lg:p-9"><h2 className="text-2xl font-black">My Subjects</h2><p className="mt-1 text-sm text-slate-500">Choose any NCERT class and build your chapter map.</p><div className="mt-6 flex flex-wrap gap-2">{classes.map(c=><button key={c} onClick={()=>setClassNo(c)} className={`rounded-lg px-3 py-2 text-xs font-bold ${classNo===c?'bg-[#12395b] text-white':'bg-slate-100 text-slate-600'}`}>Class {c}</button>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{subjects.map(s=><button key={s} onClick={()=>setSubject(s)} className={`rounded-2xl border p-5 text-left ${subject===s?'border-blue-300 bg-blue-50':'border-slate-200 bg-white hover:border-blue-200'}`}><BookOpen size={18} className="text-[#1769e0]"/><b className="mt-3 block">{s}</b><span className="mt-1 block text-xs text-slate-500">View chapters →</span></button>)}</div></section>}
function Tests({go}:{go:(s:string)=>void}){return <section className="card rounded-3xl p-6 lg:p-9"><h2 className="text-2xl font-black">Tests & Mock Exams</h2><p className="mt-1 text-sm text-slate-500">Build confidence from school exams to JEE/NEET-level practice.</p><div className="mt-6 grid gap-4 md:grid-cols-3">{[['Chapter test','10 questions','Adaptive'],['Full mock','90 minutes','Exam mode'],['JEE / NEET','Advanced','Competition']].map(x=><button onClick={()=>go('Practice')} key={x[0]} className="rounded-2xl border border-slate-200 p-5 text-left hover:border-blue-300 hover:shadow-sm"><Trophy size={18} className="text-[#1769e0]"/><b className="mt-4 block">{x[0]}</b><span className="mt-1 block text-sm text-slate-500">{x[1]} • {x[2]}</span><span className="mt-4 block text-xs font-bold text-[#1769e0]">Start →</span></button>)}</div></section>}
function Progress(){return <section className="card rounded-3xl p-6 lg:p-9"><h2 className="text-2xl font-black">Progress & Knowledge Map</h2><p className="mt-1 text-sm text-slate-500">Mastery is based on practice accuracy, recency and difficulty.</p><div className="mt-7 grid gap-4 md:grid-cols-3"><Stat title="Concept mastery" value="73%" note="+8% this month"/><Stat title="Practice accuracy" value="76%" note="184 questions"/><Stat title="Readiness" value="78%" note="Good trajectory"/></div><div className="mt-6 rounded-2xl bg-slate-50 p-5"><b>Learning priorities</b><div className="mt-4 space-y-4"><Metric l="Current Electricity" v={43}/><Metric l="Electrostatics" v={67}/><Metric l="Integration" v={72}/><Metric l="Chemical Bonding" v={88}/></div></div></section>}
function Metric({l,v}:{l:string;v:number}){return <div className="mt-4"><div className="mb-1 flex justify-between text-xs font-semibold text-slate-500"><span>{l}</span><span>{v}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-[#1769e0]" style={{width:`${v}%`}}/></div></div>}
function Stat({title,value,note}:{title:string;value:string;note:string}){return <div className="rounded-2xl border border-slate-200 p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{title}</p><b className="mt-2 block text-2xl">{value}</b><span className="mt-1 block text-xs text-slate-400">{note}</span></div>}
function Arrow(){return <ChevronRight size={16}/>}
