'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Brain,Camera,ImagePlus,Mic} from 'lucide-react';

type Profile={classNo:string;targetExam:string};
export default function TutorPage(){
 const[p,setP]=useState<Profile>({classNo:'12',targetExam:'NCERT'});const[q,setQ]=useState(''),[answer,setAnswer]=useState(''),[image,setImage]=useState(''),[busy,setBusy]=useState(false),[listening,setListening]=useState(false);const[context,setContext]=useState({classNo:'12',subject:'Physics',chapter:'',track:'NCERT'});const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{const s=new URLSearchParams(window.location.search);setContext({classNo:s.get('class')||'12',subject:s.get('subject')||'Physics',chapter:s.get('chapter')||'',track:s.get('track')||'NCERT'});fetch('/api/dashboard').then(r=>r.ok?r.json():null).then(d=>d&&setP(d.profile)).catch(()=>{})},[]);
 function voice(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){alert('Use Chrome on Android for voice input.');return}const r=new SR();r.lang='en-IN';r.onstart=()=>setListening(true);r.onresult=(e:any)=>setQ(v=>(v?v+' ':'')+e.results[0][0].transcript);r.onend=()=>setListening(false);r.start()}
 function photo(f:File){const rd=new FileReader();rd.onload=()=>setImage(String(rd.result));rd.readAsDataURL(f)}
 async function ask(){if(!q.trim()&&!image)return;setBusy(true);setAnswer('');try{const contextualQuestion=`You are helping a Class ${context.classNo} student studying ${context.subject}${context.chapter?` — chapter: ${context.chapter}`:''}. Target: ${context.track}. Answer according to the student's level, prioritize NCERT concepts for school learning, and for JEE/NEET give appropriately rigorous preparation. Student asks: ${q}`;const r=await fetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:contextualQuestion,classNo:context.classNo,subject:context.subject,chapter:context.chapter,imageData:image,targetExam:context.track||p.targetExam})});const d=await r.json();setAnswer(d.answer||d.error||'No answer returned.')}catch{setAnswer('Unable to reach the AI service.')}finally{setBusy(false)}}
 return <main className="min-h-screen grid-bg p-5 lg:p-10"><div className="mx-auto max-w-4xl"><a href="/dashboard" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Dashboard</a><section className="card mt-5 rounded-3xl p-6 lg:p-9"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-[#1769e0]"><Brain/></div><div><h1 className="text-2xl font-black">StudyFlow AI Tutor</h1><p className="text-sm text-slate-500">Class {context.classNo} • {context.subject}{context.chapter?` • ${context.chapter}`:''} • {context.track}</p></div></div>{context.chapter&&<div className="mt-5 rounded-2xl bg-blue-50 p-4 text-sm text-blue-900"><b>Chapter context:</b> {context.chapter}. Ask anything about this chapter.</div>}<div className="relative mt-5"><textarea value={q} onChange={e=>setQ(e.target.value)} className="min-h-40 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 pr-14 text-sm outline-none focus:border-blue-400 focus:bg-white" placeholder="Ask your doubt or speak it…"/><button onClick={voice} className={`absolute bottom-3 right-3 rounded-full border p-3 ${listening?'bg-red-50 text-red-600':'bg-white'}`}><Mic size={18}/></button></div>{image&&<div className="mt-3 flex items-center gap-3 rounded-2xl bg-blue-50 p-3"><img src={image} alt="Doubt" className="h-24 w-24 rounded-xl object-cover"/><button onClick={()=>setImage('')} className="text-xs font-bold text-red-600">Remove</button></div>}<div className="mt-3 flex flex-wrap gap-2"><input ref={file} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>e.target.files?.[0]&&photo(e.target.files[0])}/><button onClick={()=>file.current?.click()} className="flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><ImagePlus size={17}/> Upload doubt photo</button><button onClick={()=>file.current?.click()} className="flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><Camera size={17}/> Take photo</button><button onClick={ask} disabled={busy||(!q.trim()&&!image)} className="btn-primary rounded-xl px-5 py-2.5 text-sm font-bold disabled:opacity-50">{busy?'Thinking…':'Ask StudyFlow AI'}</button></div>{answer&&<div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><b className="text-[#1769e0]">StudyFlow AI</b><div className="mt-3 whitespace-pre-wrap text-sm leading-7">{answer}</div></div>}</section></div></main>}
