'use client';
import {useEffect,useState} from 'react';
import {Brain,GraduationCap,LogOut,Menu,UserRound,X,Target,MessageCircle,BarChart3,HeartHandshake} from 'lucide-react';
import {createClient} from '../../lib/supabase/client';

type D={user:{displayName:string};profile:{classNo:string;targetExam:string};stats:{readiness:number;accuracy:number;masteryAverage:number;totalAttempts:number;completedMinutes:number;streak:number;weakCount:number};weakTopics:any[]};
const exams=['NCERT','JEE Main','JEE Advanced','NEET UG'];

export default function Dashboard(){
 const[d,setD]=useState<D|null>(null),[tab,setTab]=useState('Dashboard'),[classNo,setClassNo]=useState('12'),[target,setTarget]=useState('NCERT'),[open,setOpen]=useState(false),[msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/dashboard',{cache:'no-store'});if(r.status===401){location.href='/login';return}const x=await r.json();if(r.ok){setD(x);setClassNo(x.profile.classNo);setTarget(x.profile.targetExam)}else setMsg(x.error||'Unable to load dashboard')}
 useEffect(()=>{load()},[]);
 async function save(){const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({classNo,targetExam:target})});setMsg(r.ok?'Profile saved.':(await r.json()).error||'Save failed');if(r.ok)load()}
 async function logout(){await createClient().auth.signOut();location.href='/login'}
 if(!d)return <main className="min-h-screen grid-bg flex items-center justify-center"><div className="card rounded-3xl p-8 text-center"><Brain className="mx-auto text-[#1769e0]"/><b className="mt-3 block">Loading StudyFlow…</b></div></main>;
 const nav=[['Dashboard',BarChart3],['AI Tutor',MessageCircle],['NJACP Companion',HeartHandshake],['Practice',Target],['My Subjects',UserRound]] as const;
 return <main className="min-h-screen grid-bg"><div className="flex min-h-screen"><aside className={`${open?'translate-x-0':'-translate-x-full'} fixed inset-y-0 z-50 w-72 border-r bg-white p-5 transition-transform lg:static lg:translate-x-0`}><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#12395b] text-white"><GraduationCap size={20}/></div><b>StudyFlow</b></div><button className="lg:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav className="mt-8 space-y-1">{nav.map(([n,I])=><button key={n} onClick={()=>{setTab(n);setOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${tab===n?'bg-[#12395b] text-white':'text-slate-500 hover:bg-slate-50'}`}><I size={17}/>{n}</button>)}</nav><button onClick={logout} className="mt-8 flex w-full items-center gap-2 rounded-xl px-3 py-3 text-sm font-bold text-slate-500"><LogOut size={16}/>Sign out</button></aside><section className="min-w-0 flex-1"><header className="flex h-20 items-center gap-3 border-b bg-white/90 px-5 backdrop-blur lg:px-10"><button className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div><p className="text-xs text-slate-400">Personal learning workspace</p><h1 className="text-xl font-black">{tab==='Dashboard'?`Welcome, ${d.user.displayName.split(' ')[0]} 👋`:tab}</h1></div></header><div className="mx-auto max-w-6xl space-y-6 p-5 lg:p-10">{tab==='Dashboard'&&<Home d={d} go={setTab}/>} {tab==='My Subjects'&&<Profile d={d} classNo={classNo} setClassNo={setClassNo} target={target} setTarget={setTarget} save={save} msg={msg}/>} {tab==='AI Tutor'&&<section className="card rounded-3xl p-8"><h2 className="text-2xl font-black">AI Tutor</h2><p className="mt-2 text-slate-500">Text, voice and photo doubt solving with your saved class and target.</p><a href="/tutor" className="btn-primary mt-5 inline-block rounded-xl px-5 py-3 text-sm font-bold">Open AI Tutor</a></section>} {tab==='NJACP Companion'&&<section className="card overflow-hidden rounded-3xl p-0"><div className="flex items-center justify-between border-b p-6"><div><h2 className="text-2xl font-black">NJACP</h2><p className="mt-1 text-slate-500">A non-judgmental space for school pressure, focus and everyday thoughts.</p></div><HeartHandshake className="text-[#1769e0]"/></div><div className="p-6"><a href="/companion" className="btn-primary inline-block rounded-xl px-5 py-3 text-sm font-bold">Open NJACP Companion →</a></div></section>} {tab==='Practice'&&<section className="card rounded-3xl p-8"><h2 className="text-2xl font-black">Adaptive Practice</h2><p className="mt-2 text-slate-500">Generate NCERT/JEE/NEET-style questions and track your answers.</p><a href="/practice" className="btn-primary mt-5 inline-block rounded-xl px-5 py-3 text-sm font-bold">Open Practice</a></section>}</div></section></div></main>;
}
function Home({d,go}:{d:D;go:(x:string)=>void}){const s=d.stats;return <><div className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-3xl app-gradient p-8 text-white"><p className="text-xs font-bold uppercase tracking-wider text-blue-200">Live adaptive dashboard</p><h2 className="mt-4 text-4xl font-black">Know what to study.<br/><span className="text-blue-200">Know why it matters.</span></h2><p className="mt-4 text-sm leading-6 text-blue-50/80">These numbers are calculated from your actual Supabase learning history.</p><button onClick={()=>go('Practice')} className="mt-6 rounded-xl bg-white px-5 py-3 text-sm font-bold text-[#12395b]">Continue learning →</button></div><div className="card rounded-3xl p-6"><p className="text-xs font-bold uppercase text-slate-400">Exam readiness</p><b className="mt-1 block text-4xl">{s.readiness}%</b><Bar label="Concept mastery" n={s.masteryAverage}/><Bar label="Practice accuracy" n={s.accuracy}/></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat title="Questions" value={s.totalAttempts} note={`${s.accuracy}% accuracy`}/><Stat title="Weak topics" value={s.weakCount} note="AI priority"/><Stat title="Streak" value={`${s.streak} days`} note="Keep going"/><Stat title="Study time" value={`${s.completedMinutes} min`} note="Completed"/></div><div className="card rounded-3xl p-6"><h3 className="text-lg font-black">Priority topics</h3><p className="mt-1 text-sm text-slate-500">Lowest mastery first.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{d.weakTopics.length?d.weakTopics.slice(0,6).map(t=><button key={t.topic+t.subject} onClick={()=>go('Practice')} className="rounded-2xl border p-4 text-left hover:border-blue-300"><div className="flex justify-between"><b className="text-sm">{t.topic}</b><b className="text-xs">{t.mastery}%</b></div><p className="mt-1 text-xs text-slate-400">{t.subject} • {t.chapter||'Topic'}</p><Bar label="" n={t.mastery}/></button>):<p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Complete your first practice set and StudyFlow will build your weak-topic queue.</p>}</div></div></>}
function Profile({d,classNo,setClassNo,target,setTarget,save,msg}:{d:D;classNo:string;setClassNo:(x:string)=>void;target:string;setTarget:(x:string)=>void;save:()=>void;msg:string}){return <section className="card mx-auto max-w-2xl rounded-3xl p-7"><div className="flex items-center gap-3"><UserRound className="text-[#1769e0]"/><div><h2 className="text-2xl font-black">My learning profile</h2><p className="text-sm text-slate-500">{d.user.displayName}</p></div></div><label className="mt-7 block text-xs font-bold uppercase text-slate-400">Class<select value={classNo} onChange={e=>setClassNo(e.target.value)} className="mt-2 w-full rounded-xl border p-3 text-sm">{Array.from({length:7},(_,i)=>i+6).map(x=><option key={x} value={x}>Class {x}</option>)}</select></label><label className="mt-4 block text-xs font-bold uppercase text-slate-400">Target exam<select value={target} onChange={e=>setTarget(e.target.value)} className="mt-2 w-full rounded-xl border p-3 text-sm">{exams.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={save} className="btn-primary mt-5 rounded-xl px-5 py-3 text-sm font-bold">Save profile</button>{msg&&<p className="mt-3 text-sm text-slate-500">{msg}</p>}</section>}
function Bar({label,n}:{label:string;n:number}){return <div className="mt-4">{label&&<div className="flex justify-between text-xs text-slate-500"><span>{label}</span><span>{n}%</span></div>}<div className="mt-1 h-1.5 rounded-full bg-slate-100"><div className="h-full bg-[#1769e0]" style={{width:`${Math.max(0,Math.min(100,n))}%`}}/></div></div>}
function Stat({title,value,note}:{title:string;value:string|number;note:string}){return <div className="card rounded-2xl p-5"><p className="text-xs font-bold uppercase text-slate-400">{title}</p><b className="mt-2 block text-2xl">{value}</b><span className="text-xs text-slate-400">{note}</span></div>}
